insert into sections (title, vietnamese) values ('Appetizers', 'Món Khai Vị');
insert into sections (title, vietnamese) values ('Phở - Rice Noodle Soup', 'Bún bò Huế');
insert into sections (title, vietnamese) values ('Vietnamese Broken Rice Platters', 'Cơm Đĩa');
insert into sections (title, vietnamese) values ('Vietnamese Fried Rice', 'Cơm Chiên');
insert into sections (title) values ('Vermicelli Bowls');
insert into sections (title, vietnamese) values ('Vermicelli Platters - Rice Vermicelli Woven', 'Bánh hỏi');
insert into sections (title) values ('Special Vietnamese Noodle Soups');
insert into sections (title) values ('The Wok - Stir Fried Noodles');
insert into sections (title) values ('Thai - Dishes (Spicy)');
insert into sections (title) values ('Vegetarian');
insert into sections (title) values ('Desserts');
insert into sections (title) values ('Bubble Tea - Slushy or Milk Tea');
insert into sections (title) values ('Soft Drinks');
insert into sections (title) values ('Party Trays');
