DROP TABLE IF EXISTS items CASCADE;

CREATE TABLE items (
  id SERIAL PRIMARY KEY NOT NULL,
  section VARCHAR(50) NOT NULL,
  name VARCHAR(50) NOT NULL,
  vietnamese VARCHAR(50) NOT NULL,
  base_price NUMERIC(10, 2) NOT NULL
);
